# Generated by Django 2.2.5 on 2019-09-26 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=20, verbose_name='state')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
            ],
        ),
        migrations.CreateModel(
            name='issue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=300, verbose_name='Small description')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Full description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Status', verbose_name='Status')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='webapp.Type', verbose_name='Type')),
            ],
        ),
    ]
