# Generated by Django 2.2.5 on 2019-10-09 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Project name')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Project description')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Date updated')),
            ],
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.Project', verbose_name='Project'),
        ),
    ]
