# Generated by Django 2.2.5 on 2019-10-09 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_auto_20191009_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='webapp.Issue', verbose_name='Issue'),
        ),
    ]
