# Generated by Django 2.2.5 on 2019-10-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_auto_20191009_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='issue',
        ),
        migrations.AddField(
            model_name='issue',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='issues', to='webapp.Project', verbose_name='Project'),
        ),
    ]
