# Generated by Django 2.2.5 on 2019-10-14 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_auto_20191010_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Time updated'),
        ),
    ]
