# Generated by Django 2.2.5 on 2019-10-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_issue_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='issue_type', to='webapp.Type', verbose_name='Type'),
        ),
    ]
